# navbar
menu:
  Home: /
  Archives: /archives/
  About: /about/

# site icon
favicon: /favicon.png
appleicon: /favicon.png

# comments
comments:
  post: true
  about: true

# article directory sidebar
sidebar: true

# Analytics
## Baidu Analytics
# baidu_analytics: Your baidu Analytics ID
## Google Analytics
google_analytics: UA-4178606-9

# Comments
## Duoshuo
# duoshuo_shortname: Your duoshuo ID
# Disqus
disqus_shortname: lyric-im

award:
  btc_addr: 1PqcopKzdg8ZM22f6cAoCpJ8WS7xvsFJ3n
  btc_qrcode: /assets/btc_qrcode.png
  eth_addr: '0x63D3eFE04c1266fb9fA4690360332F9B1cd93B47'
  eth_qrcode: /assets/eth_qrcode.png
  wechat_addr: '点击此处展示赞赏码' 
  wechat_qrcode: /assets/wechat_qrcode.jpg

excerpt_link: 阅读全文
